version: '3'

services:
  apache-airflow:
    image: apache-airflow:latest

    volumes:
      - ./airflow:/opt/airflow
      # - ./dags:/opt/airflow/dags
      # - ./db:/opt/airflow/db
      
    ports:
      - "8080:8080"
    
    command: airflow standalone